# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piston', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'managed': False},
        ),
    ]
