# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piston', '0003_auto_20160112_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='timestamp',
            field=models.IntegerField(default=1),
        ),
    ]
